[package]
name = "loadTesting"
version = "0.0.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "kt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
clap = { version = "4.4.1", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.0"
hyper = { version = "1.3.1", features = ["full"] }
hyper-util = { version = "0.1.4", features = ["full"] }
http-body-util = { version = "0.1" }
futures = "0.3.29"
mlua = { version = "0.9.1", features = [
    "lua54",
    "vendored",
    "async",
    "macros",
] }
hyper-rustls = { version = "0.27.1", default-features = false, features = [
    "logging",
    "ring",
    "tls12",
    "http1",
    "http2",
] }
rustls = { version = "0.23.8", default-features = false, features = [
    "logging",
    "ring",
    "tls12",
] }
itertools = "0.12.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
webpki-roots = "0.26.1"
