[package]
name = "loadTesting"
version = "0.0.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "kt"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["full"] }
clap = { version = "4.5.26", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"
hyper = { version = "1.5.2", features = ["full"] }
hyper-util = { version = "0.1.10", features = ["full"] }
http-body-util = { version = "0.1.2" }
futures = "0.3.31"
mlua = { version = "0.10.2", features = [
    "lua54",
    "vendored",
    "async",
    "macros",
] }
hyper-rustls = { version = "0.27.5", default-features = false, features = [
    "logging",
    "ring",
    "tls12",
    "http1",
    "http2",
] }
rustls = { version = "0.23.21", default-features = false, features = [
    "logging",
    "ring",
    "tls12",
] }
itertools = "0.14.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
webpki-roots = "0.26.7"
