[package]
name = "loadTesting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.1", features = ["derive"] }
log = "0.4.20"
env_logger= "0.10.0"
hyper = { version = "0.14", features = ["full"] }
futures = "0.3.29"
mlua = { version = "0.9.1", features = ["lua54", "vendored","async","macros"] }
